---
title: "network"
author: "Donald R. Williams"
date: "3/14/2021"
output: html_document
---

```{r}
library(GGMncv)
library(corpcor)
library(boot)
library(ggplot2)
library(dplyr)
```

# Plot 3B
## Simulation
```{r}
# glasso
reg_func <- function(data, i, ic,...){
  
  d <- data[i,]
  
  n <- nrow(d)
  
  fit <- GGMncv::ggmncv(cor(d),  
                        n = n, 
                        ic = ic,
                        penalty = "lasso",
                        progress = FALSE,...)
  
  fit$P[upper.tri(diag(ncol(d)))]

}

# sample covariance matrix
nonreg_func <- function(data, i){
  
  d <- data[i,]
  
  corpcor::cor2pcor(cor(d))[upper.tri(diag(ncol(d)))]
  
}

# PTSD data
Yorig <- BGGM::ptsd[,1:20]

# PTSD correlations
S <- cor(Yorig)

# PTSD partial correlations
pcors <- corpcor::cor2pcor(S)

# set to zero (true network)
true_pcors <- ifelse(abs(pcors) < 0.05, 0, pcors)

# true correlation matrix
S <- corpcor::pcor2cor(true_pcors)

# id of non-zeros
which_edges <- which(true_pcors[upper.tri(true_pcors)] != 0)

# true edges
edges <- true_pcors[upper.tri(true_pcors)][which_edges]



cl <- parallel::makeCluster(8)

n <-  c(
  250, 500, 1000, 2500, 10000, 25000, 50000
  )

iter <- 5

mat_ebic <- matrix(0, nrow = iter, length(edges))
mat_bic <- matrix(0, nrow = iter, length(edges))
mat_nonreg <- matrix(0, nrow = iter, length(edges))

res_j <- list()

for(j in 1:length(n)){
  for(i in 1:iter){
    
    message(paste0("sample size = ", n[j], "; iter = ", i))
    
    Y <- MASS::mvrnorm(n = n[j], rep(0, 20), Sigma = S)

    reg_ebic <- boot(data = Y, 
                statistic = reg_func, 
                R = 500, 
                ic = "ebic",
                ncpus = 8, 
                cl = cl,
                parallel = "snow")
    
    reg_bic <- boot(data = Y,
                statistic = reg_func,
                R = 500,
                ic = "ebic", 
                ebic_gamma = 0,
                ncpus = 8, cl = cl,
                parallel = "snow")


nonreg <- boot(data = Y, 
                statistic = nonreg_func, 
                R = 500, 
                ncpus = 8, cl = cl,
                parallel = "snow")


ebic_cis <- as.data.frame(
  t(apply(reg_ebic$t[,which_edges], 2,quantile, 
          probs = c(0.05, 0.95)))
  )

bic_cis <- as.data.frame(
  t(apply(reg_bic$t[,which_edges], 2, 
          quantile, probs = c(0.05, 0.95)))
)

nonreg_cis <- as.data.frame(
  t(apply(nonreg$t[,which_edges], 2,quantile, 
          probs = c(0.05, 0.95)))
)

mat_ebic[i,] <- ifelse(ebic_cis$`5%` < edges & ebic_cis$`95%` > edges, 1, 0 )
mat_bic[i,] <- ifelse(bic_cis$`5%` < edges & bic_cis$`95%` > edges, 1, 0 )
mat_nonreg[i,] <- ifelse(nonreg_cis$`5%` < edges & nonreg_cis$`95%` > edges,1,0 )

}

results <- rbind.data.frame(
data.frame(model = "ebic", cover =  rowMeans(mat_ebic)),
data.frame(model = "bic", cover =  rowMeans(mat_bic)),
data.frame(model = "nonreg", cover =  rowMeans(mat_nonreg))
)
results$n <- n[j]
res_j[[j]] <- results
}

# commented out to prevent overwriting
# files in the folder

# ave_coverage <- res_j
# save(ave_coverage, file = "ave_coverage.Rda")
```


## Make Figure: Figure 3B
```{r}
load("ave_coverage.Rda")

plot_3B <-
  do.call(rbind.data.frame, ave_coverage) %>%
  group_by(model, n) %>%
  summarise(
    mu = mean(cover),
    ub = max(cover),
    lb = min(cover),
    sd = sd(cover)
  ) %>%
  ggplot(aes(x = as.factor(n),
             y = mu,
             group = model)) +
  geom_blank() +
  geom_hline(yintercept = 0.90, alpha = 0.5) +
  annotate(
    geom = "rect",
    xmin = -Inf,
    xmax = 1.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = "rect",
    xmin = 2.5,
    xmax = 3.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = "rect",
    xmin = 4.5,
    xmax = 5.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = "rect",
    xmin = 6.5,
    xmax = Inf,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = 'segment',
    x = c(1.5, 2.5, 3.5, 4.5, 5.5, 6.5),
    xend = c(1.5, 2.5, 3.5, 4.5, 5.5, 6.5),
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  
  geom_line(position = position_dodge(1),
            aes(color = model),
            alpha = 0.5) +
  scale_y_continuous(limits = c(0.20, 1)) +
  geom_errorbar(aes(ymax = mu + sd,
                    ymin = mu - sd),
                position = position_dodge(1),
                width = 0.25) +
  geom_point(position = position_dodge(1),
             size = 3,
             color = "black") +
  geom_point(position = position_dodge(1), size = 2.5,
             aes(color = model)) +
  
  theme_bw() +
  theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    panel.grid = element_blank(),
    legend.title = element_blank(),
    legend.text.align = 0,
    legend.position = "top"
  ) +
  ylab(expression(paste("Average Coverage (", rho != 0, ")"))) +
  xlab("Sample Size") +
  scale_y_continuous(limits = c(0.25, 1),
                     breaks = seq(.3, 1, 0.1)) +
  scale_color_manual(
    values = c("#0072B2", "#CC79A7", "#999999"),
    labels = c(expression(gamma ~ "= 0.5"),
               expression(gamma ~ "= 0"),
               "Non-reg"),
    breaks  = c("ebic", "bic", "nonreg")
    
  )


```


# Plot 3C
## Simulation
```{r}
# PTSD data
Yorig <- BGGM::ptsd[,1:20]
p <- ncol(Yorig)
S <- cor(Yorig)
pcors <- corpcor::cor2pcor(S)

# true network: note rounding
true_pcors <- round(ifelse(abs(pcors) < 0.05, 0, pcors), 1)

# true correlation matrix
S <- corpcor::pcor2cor(true_pcors)

# edge location
which_edges <- which(true_pcors[upper.tri(true_pcors)] != 0)

# true edges
edges <- true_pcors[upper.tri(true_pcors)]


iter <- 1000

cl <- parallel::makeCluster(8)

mat_bic <- matrix(0, nrow = iter, length(edges))
mat_nonreg <- matrix(0, nrow = iter, length(edges))

n <- c(500, 2500)

res_j <- list()

for(j in 1:length(n)){
  for(i in 1:iter){
    message(paste0("sample size = ", n[j], "; iter = ", i))
  Y <- MASS::mvrnorm(n = n[j], rep(0, p), Sigma = S)
  
  reg_bic <- boot(data = Y,
                  statistic = reg_func,
                  R = 500,
                  ic = "ebic",
                  ncpus = 8, cl = cl,
                  parallel = "snow")
  
  nonreg <- boot(data = Y, 
                 statistic = nonreg_func, 
                 R = 500, 
                 ncpus = 8, cl = cl,
                 parallel = "snow")
  
  
  bic_cis <- as.data.frame(
    t(apply(reg_bic$t, 2,quantile, 
            probs = c(0.05, 0.95)))
  )
  
  nonreg_cis <- as.data.frame(
    t(apply(nonreg$t, 2,quantile,
            probs = c(0.05, 0.95)))
  )
  
  mat_bic[i,] <- ifelse(bic_cis$`5%` <= edges & bic_cis$`95%` >= edges, 1, 0 )
  mat_nonreg[i,] <- ifelse(nonreg_cis$`5%` <= edges & nonreg_cis$`95%` >= edges,1,0 )

}

res_j[[j]] <- rbind.data.frame(
data.frame(
  model = "lasso",
  n = n[j],
  edges = edges, 
  cover = colMeans(mat_bic)
),

data.frame(
  model = "nonreg",
  n = n[j],
  edges = edges, 
  cover = colMeans(mat_nonreg)
))

}

# commented out to prevent overwriting
# files in the folder

# abs_sim <- res_j
# save(abs_sim, file = "abs_sim.Rda")
```

## Make Figure: Figure 3C
```{r}
load(file = "abs_sim.Rda")

plot_3C <- do.call(rbind, abs_sim) %>%
  ggplot(aes(
    x = as.factor(abs(edges)),
    y = cover,
    color = as.factor(model)
  )) +
  geom_hline(yintercept = 0.90, alpha = 0.5) +
  annotate(
    geom = "rect",
    xmin = -Inf,
    xmax = 1.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = "rect",
    xmin = 2.5,
    xmax = 3.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  annotate(
    geom = "rect",
    xmin = 4.5,
    xmax = 5.5,
    ymin = -Inf,
    ymax = Inf,
    fill = "grey97",
    alpha = 0.25
  ) +
  
  annotate(
    geom = 'segment',
    x = 1.5,
    xend = 1.5,
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  annotate(
    geom = 'segment',
    x = 2.5,
    xend = 2.5,
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  annotate(
    geom = 'segment',
    x = 3.5,
    xend = 3.5,
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  annotate(
    geom = 'segment',
    x = 4.5,
    xend = 4.5,
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  annotate(
    geom = 'segment',
    x = 5.5,
    xend = 5.5,
    y = -Inf,
    yend = Inf,
    linetype = "dotted",
    alpha = 0.1
  ) +
  geom_point(
    aes(size = as.factor(n)),
    position =
      position_jitterdodge(
        jitter.width = 0.15,
        jitter.height = 0,
        dodge.width = 1
      ),
    alpha = 0.5
  ) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid = element_blank(),
    panel.grid.minor.x = element_blank(),
    legend.text.align = 0
  ) +
  scale_size_manual(values = c(1, 3),
                    name = expression(italic(N))) +
  
  xlab(expression(italic(True) ~ "Value"))  +
  ylab("Coverage") +
  coord_flip()  +
  scale_x_discrete(
    expand = c(0, 0),
    labels = c(
      expression(rho ~ " = 0"),
      expression("|" * rho * "|" ~ " = 0.1"),
      expression("|" * rho * "|" ~ " = 0.2"),
      expression("|" * rho * "|" ~ " = 0.3"),
      expression("|" * rho * "|" ~ " = 0.4"),
      expression("|" * rho * "|" ~ " = 0.5")
    )
  )  +
  scale_color_manual(
    name = "",
    values = c("#E69F00",
               "#009E73"),
    labels = c(expression(gamma ~ "= 0.5"),
               "Non-reg")
  ) +
  guides(
    colour = guide_legend(order = 1,
                          override.aes = list(alpha = 1,
                                              size = 3)),
    size = guide_legend(order = 2, override.aes = list(alpha = 1))
  ) +
  scale_y_continuous(limits = c(0, 1), 
                     breaks = seq(0, 1, 0.1))
```