---
title: "regression_exp_1"
author: "Donny Williams"
date: "3/14/2021"
output: html_document
---

# Packages
```{r}
library(boot)
library(cowplot)
library(glmnet)
library(ggplot2)
library(dplyr)
```

# Plot 2B
## Regularized
```{r}
# true betas
betas <- c(seq(0.1, 1, 0.1), rep(0, 10))


boot_func <- function(data, i, gamma, lambda){
  
  d <- data[i,]
  
  y <- d[,1]
  
  X <- d[,-1]
  # fit lasso
  fit <- glmnet::glmnet(X, y)
  
  # the number of lambdas
  n_lambda <- length(fit$lambda)
  
  # compute BIC for each lambda
  
  BIC <- lapply(1:n_lambda, function(x) {
    
    pred <- glmnet::predict.glmnet(fit, 
                                   newx = X, 
                                   s = fit$lambda[x])
    
    # residual sum of squares
    RSS <- sum((pred - y)^2)
    
    # number of observations
    n <- length(y)
    
    # number of predictors
    p <- ncol(X)
    # BIC (or EBIC if gamma > 0)
    BIC <- n * log(RSS/n) + fit$df[x] * log(n) + 4 * fit$df[x] * gamma * log(p)
    
    # return BIC
    BIC
    
  })
  
  # selected betas
  beta_selected <- fit$beta[,which.min(BIC)]
  
  # return selected betas
  beta_selected
  
}

# number of clusters
cl <- parallel::makeCluster(4)

# simulation trials
iter <- 500

# matrix for storage (only non-zero)
mat <- matrix(0, iter, 10)

# sample sizes
n <- c(250, 500, 1000)

# additions to BIC
gamma <- c(0, 0.5, 1)

# storage
ls_j <- list()
ls_g <- list()

for(j in 1:3){
  
  for(g in 1:3){

  for(i in 1:iter){
  
  message(paste0("sample size = ", n[j], "; gamma = ", gamma[g], "; iter = ", i))
  
  X <- MASS::mvrnorm(n[j], rep(0, 20), diag(20))
  
  # SNR = 1
  sigma <- sqrt(as.numeric(crossprod(betas, diag(20) %*% betas) / 1))
  
  y <- X %*% betas + rnorm(n[j], 0, sigma)
  
  dat <- cbind(y, X)
  
  boot_res <- boot(data = dat, 
              statistic = boot_func, 
              R = 500, 
              gamma = gamma[g],
              ncpus = 8, cl = cl,
              parallel = "snow")

  
  # 90 % CIs
  cis <-  as.data.frame(
    t(apply(boot_res$t,MARGIN = 2, quantile, c(0.05, 0.95)))[1:10,]
    )

  cis$betas <- betas[1:10]
  
  # coverage
  mat[i,] <- ifelse(cis[,1] < betas[1:10] & 
                    cis[,2] > betas[1:10], 1, 0)
  
  }
    # summary after all simulation trials 
    res_dat <- data.frame(
      coverage = colMeans(mat), 
      betas = betas[1:10], 
      gamma = gamma[g])
    
    # res_dat$gamma <- gamma[g]
    # store
    ls_g[[g]] <- res_dat
    }
  
  ls_j[[j]] <- data.frame(
    do.call(rbind.data.frame, ls_g), 
    n = n[j]
    )
  
}

# commented out to prevent overwriting
# files in the folder

# ideal_situation <- ls_j
# save(ideal_situation, file = "ideal_situation.Rda")
```


## Non-Regularized
```{r}
# true betas
betas <- c(seq(0.1, 1, 0.1), rep(0, 10))

boot_lm <- function(data, i){
  
  d <- data[i,]
  
  y <- d[,1]
  
  X <- d[,-1]
  
  coef(lm(y ~ X))[-1]
  
}

mat <- matrix(0, iter, 10)

n <- c(250, 500, 1000)

ls_j <- list()

for(j in 1:3){
    
    for(i in 1:iter){
      
      message(paste0("sample size = ", n[j], "; iter = ", i))
      
      X <- MASS::mvrnorm(n[j], rep(0, 20), diag(20))
      
      # SNR = 1
      sigma <- sqrt(as.numeric(crossprod(betas, diag(20) %*% betas) / 1))
      
      y <- X %*% betas + rnorm(n[j], 0, sigma)
      
      dat <- cbind(y, X)
      
      
      boot_res <- boot(data = dat,
                       statistic = boot_lm,
                       R = 500)
      
      # cis
      cis <-  as.data.frame(t(apply(
        boot_res$t, MARGIN = 2, quantile, c(0.05, 0.95)
      ))[1:10, ])
      
      cis$betas <- betas[1:10]
      
      mat[i,] <- ifelse(cis[,1] < betas[1:10] & 
                          cis[,2] > betas[1:10], 1, 0)
      }
    
  res_dat <- data.frame(coverage = colMeans(mat), 
                          betas = betas[1:10], 
                          n = n[j])
    ls_j[[j]] <- res_dat
}

# commented out to prevent overwriting
# files in the folder

# ideal_situation_lm <- ls_j
# save(ideal_situation_lm, file = "ideal_situation_lm.Rda")
```

## Make Figure: Figure 2B
```{r}
load(file = "ideal_situation.Rda")
load(file = "ideal_situation_lm.Rda")

dat_lm <- do.call(rbind.data.frame, ideal_situation_lm)
# dummy gamma value
dat_lm$gamma <- 2

# combine lasso and non-reg
dat_new <- rbind.data.frame(
do.call(rbind.data.frame, ideal_situation) , 
dat_lm) 

dat_new$gamma_new <- factor(
  as.factor(dat_new$gamma), 
  levels = c(1,0.5,0, 2),
  labels =c(1,0.5,0,2)
  )
 
dat_new$n <- as.factor(dat_new$n) 

plot_2B <-
ggplot(dat_new,
       aes(
         x = as.factor(n),
         y = coverage,
         fill = as.factor(gamma_new)
       )) +
  geom_blank() +
  geom_hline(yintercept = 0.90, alpha = 0.5) +
  annotate(geom = "rect", 
           xmin = -Inf, 
           xmax = 1.5, 
           ymin = -Inf, 
           ymax = Inf, 
           fill = "grey97", 
           alpha = 0.25)  +
  annotate(geom = "rect", 
           xmin = 2.5, 
           xmax = Inf, 
           ymin = -Inf, 
           ymax = Inf, 
           fill = "grey97", 
           alpha = 0.25)  +
   annotate(geom = 'segment', 
            x = 1.5, 
            xend = 1.5, 
            y = -Inf, 
            yend = Inf, 
            linetype = "dotted", 
            alpha = 0.1) +
  annotate(geom = 'segment', 
           x = 2.5, 
           xend = 2.5, 
           y = -Inf, 
           yend = Inf, 
           linetype ="dotted", 
           alpha = 0.1) +
  geom_point(position =  position_jitterdodge(seed = 1,
                                              jitter.width = 0.5,
                                              jitter.height = 0,
                                              dodge.width = 1),
              alpha = 0.5) +
    geom_boxplot(position = position_dodge(1), outlier.shape = NA) +
  scale_y_continuous(limits = c(0.10, 1),
                     breaks = seq(0.1,1,0.1)) +
  theme_bw() +
  theme(legend.title = element_blank(), 
         legend.position = "top", 
         panel.grid = element_blank()) +
  ylab("Coverage") +
  xlab("Sample Size") +
  scale_fill_manual(
    values = c("#CC79A7",  "#0072B2", "#009E73", "#999999"),
    labels = c(
      expression(gamma ~ "= 1"),
      expression(gamma ~ "= 0.5"),
      expression(gamma ~ "= 0"),
      "Non-reg"
    ))
    
```

# Plot 2C
## Simulation
```{r}
# true betas
betas <- c(seq(0.1, 1, 0.1), rep(0, 10))

l1_fixed <- function(data, i, lambda){
  
  d <- data[i,]
  
  y <- d[,1]
  
  X <- d[,-1]
  
  fit <- glmnet::glmnet(X, y, lambda = lambda)
  
  as.matrix(coef(fit))[-1,]

}

iter <- 1000

ls_l <- list()

lambda <- c(0, seq(0.01, 2, 
              length.out = 19)) * sqrt(log(20)/ 1000)

lambda <- round(lambda, 3)

cl <- parallel::makeCluster(8)

mat <- matrix(0, nrow = iter, ncol = 20)

for(l in 1:length(lambda)) {
  for (i in 1:iter) {
    message("lambda = ", l, "; iter = ", i)
    
    X <- MASS::mvrnorm(1000, rep(0, 20), diag(20))
    
    sigma <- sqrt(as.numeric(crossprod(betas, diag(20) %*% betas) / 1))
    
    y <- X %*% betas + rnorm(1000, 0, sigma)
    
    dat <- cbind(y, X)
    
    l1 <- boot(
      data = dat,
      statistic = l1_fixed,
      R = 500,
      lambda = lambda[l],
      ncpus = 8,
      cl = cl,
      parallel = "snow"
    )
    
    
    l1_cis <-  as.data.frame(t(apply(l1$t, MARGIN = 2, quantile, c(0.05,   0.95))))
    
    mat[i, ] <- ifelse(l1_cis[, 1] <= betas &
                         l1_cis[, 2] >= betas, 1, 0)
    
  }
  res_dat <- data.frame(coverage = colMeans(mat),
                        betas = betas,
                        lambda = lambda[l])
  ls_l[[l]] <- res_dat
}

# # commented out to prevent overwriting
# files in the folder

# tc_lambda <- ls_l
# save(tc_lambda, file = "tc_lambda.Rda")
```

## Make Figure: Figure 2C
```{r}
load(file =  "tc_lambda.Rda")


plot_2C <-
  do.call(rbind.data.frame, tc_lambda) %>%
  mutate(beta_new =
           rep(c(betas[1:10], 0, seq(
             0.001, 0.011, length.out = 9
           )), 20),
         lwd = rep(c(betas[1:10] , rep(0, 10)), 20)) %>%
  ggplot(aes(
    x = as.factor(lambda),
    y = coverage,
    group = (beta_new),
    color = (beta_new)
  )) +
  geom_blank() +
  geom_hline(yintercept = 0.90, alpha = 0.5) +
  geom_line(size = 1.5, alpha = 0.75) +
  scale_y_continuous(limits = c(0.4, 1),
                     breaks = seq(0.4, 1, 0.1)) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = "top") +
  scale_color_gradient(
    low = "black",
    high = "grey",
    breaks = seq(0, 1, 0.1),
    name = expression(beta ~ "  ")
  ) +
  ylab("Coverage") +
  guides(colour = guide_colorbar(
    title.hjust = 0.5,
    title.vjust = 0.75,
    barwidth = 12,
    ticks.lineheight = 1.5
  ))  +
  xlab("Regularization") +
  scale_x_discrete(
    labels = c(
      "Non-reg",
      rep("", 3),
      expression("0.35\U00B7" * lambda[TC]),
      rep("", 5),
      expression(lambda[TC]),
      rep("", 4),
      expression("1.55\U00B7" * lambda[TC]),
      rep("", 3),
      expression("2\U00B7" * lambda[TC])
    ),
    guide = guide_axis(angle = 55)
  ) 
```