---
title: "why_it_matters"
author: "Donald R. Williams"
date: "3/14/2021"
output: html_document
---

```{r}
library(GGMncv)
library(Matrix)
library(MASS)
library(ggridges)
```

# Plot 1
## Simulation
```{r}
# pcors 
pcors <- matrix(0, 20, 20)
pcors[1,2] <- 0
pcors[1,3] <- 0.3
pcors[1,2] <- 0.1
diag(pcors) <-1

pcors <-
as.matrix(
Matrix::forceSymmetric(pcors)
)

cors <- corpcor::pcor2cor(pcors)

mat <- matrix(0, 10000, 6)

# empirical = TRUE. sample equals true
Y <- MASS::mvrnorm(n = 500, rep(0, 20), 
                   Sigma = cors, 
                   empirical = TRUE)

ls_i <- list()

for(i in 1:10000) {
  print(i)
  
  Yboot <- Y[sample(1:500, size = 500, replace = TRUE), ]
  
  l1 <- GGMncv::ggmncv(
    cor(Yboot),
    n = 500,
    progress = FALSE,
    penalty = "lasso",
    ic = "ebic"
  )$P[upper.tri(diag(20))][1:3]
  
  nonreg <- corpcor::cor2pcor(cor(Yboot))[upper.tri(diag(20))][1:3]
  
  ls_i[[i]] <- data.frame(
    method = c(rep("l1", 3), rep("nonreg", 3)),
    est =  c(l1, nonreg),
    relation = c(1:3, 1:3)
  )
  
}
```

## Plot 1A 
```{r}
plot_1A <-
  do.call(rbind, ls_i) %>%
  mutate(method = factor(
    method,
    levels = c("nonreg", "l1"),
    labels = c("nonreg", "l1")
  )) %>%
  mutate(relation  = factor(relation,
                            levels = c(3, 1, 2), 
                            labels = c(3, 1, 2))) %>%
  ggplot(aes(
    x = est,
    y = as.factor(relation),
    fill = method
  )) +
  geom_density_ridges(
    stat = "binline",
    alpha = 0.5,
    color = "white",
    draw_baseline = TRUE,
    scale = 10,
    binwidth = 0.01,
    rel_min_height = .001
  ) +
  scale_y_discrete(expand = c(0, 0),
                   labels = c(
                     expression(rho[B][C] ~ " = 0"),
                     expression(rho[A][C] ~ " = 0.1"),
                     expression(rho[A][B] ~ " = 0.3")
                   )) +
  coord_cartesian(ylim = c(1, 4.6)) +
  annotate(
    "rect",
    xmin = -Inf,
    xmax = Inf,
    ymin = 4.5,
    ymax = Inf,
    fill = "white"
  ) +
  annotate(
    "segment",
    x = 0,
    xend = 0,
    y = 4.5,
    yend = 4.51,
    size = 1.5,
    color = "black",
    alpha = 1,
    arrow = arrow()
  ) +
  annotate(
    "segment",
    x = 0,
    xend = 0,
    y = 2.5,
    yend = 2.51,
    size = 1.5,
    color = "black",
    alpha = 1,
    arrow = arrow()
  ) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    legend.position = "top"
  ) +
  ylab(expression(italic(True) ~ "Value")) +
  xlab("Bootstrap Sampling Distribution") +
  scale_x_continuous(
    limits = c(-0.2, 0.45),
    labels = seq(-0.2, 0.4, 0.1),
    breaks = seq(-0.2, 0.4, 0.1)
  ) +
  scale_fill_manual(
    name = "",
    values = c("#CC79A7", "#0072B2"),
    labels = c("Non-reg",
               expression(L[1] ~ "-reg"))
  )

```

## Plot 1B 
```{r}
plot_1B <-
  do.call(rbind.data.frame, ls_i) %>%
  mutate(method = factor(
    method,
    levels = c("nonreg", "l1"),
    labels = c("nonreg", "l1")
  )) %>%
  mutate(relation  = factor(relation, levels = c(3, 1, 2), labels = c(3, 1, 2))) %>%
  group_by(relation, method) %>%
  summarise(lb = quantile(est, c(0.025)),
            ub = quantile(est, c(0.975)),
            med = quantile(est, c(0.5))) %>%
  ggplot(aes(x = med, color = method, y = relation)) +
  geom_blank() +
  geom_hline(yintercept = 1.5,
             linetype = "dotted",
             alpha = 0.5) +
  geom_hline(yintercept = 2.5,
             linetype = "dotted",
             alpha = 0.5) +
  annotate(
    "rect",
    xmin = -0.0930,
    xmax = 0.0976,
    ymin = -Inf,
    ymax = 1.5,
    fill = "#E69F00",
    alpha = 0.1
  ) +
  annotate(
    "rect",
    xmax = 0.376,
    xmin = 0.219,
    ymin = 2.5,
    ymax = Inf,
    fill = "#E69F00",
    alpha = 0.1
  ) +
  annotate(
    "rect",
    xmax = 0.187,
    xmin = 0.0120,
    ymin = 1.5,
    ymax = 2.5,
    fill = "#E69F00",
    alpha = 0.1
  ) +
  
  geom_errorbar(
    aes(
      xmax = ub,
      xmin = lb,
      x = med,
      color = method,
      y = relation
    ),
    position = position_dodge(1),
    width = 0,
    size = 1.25
  ) +
  scale_x_continuous(
    limits = c(-0.2, 0.45),
    labels = seq(-0.2, 0.4, 0.1),
    breaks = seq(-0.2, 0.4, 0.1)
  ) +
  geom_point(
    aes(
      group = method,
      x = med,
      y = as.factor(relation)
    ),
    position = position_dodge(1),
    color = "black",
    size = 2.5
  ) +
  
  scale_color_manual(
    name = "",
    values = c("#CC79A7", "#0072B2"),
    labels = c("Non-reg",
               expression(L[1] * "-reg"))
  ) +
  theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid = element_blank(),
    panel.grid.minor.x = element_blank(),
    legend.position = "top"
  ) +
  ylab(expression(italic(True) ~ "Value")) +
  scale_y_discrete(expand = c(0, 0),
                   labels = c(
                     expression(rho[B][C] ~ " = 0"),
                     expression(rho[A][C] ~ " = 0.1"),
                     expression(rho[A][B] ~ " = 0.3")
                   ))  +
  
  xlab("95 % Confidence Interval")

```

## Combine plots
```{r}
dummy <-
  data.frame(
    Reject = c("No", "Yes"),
    y = c(1, 2),
    alpha =  c(0.1, 1)
  )

dummy_plot <-
  ggplot(dummy, aes(
    x = Reject,
    alpha = Reject,
    fill = Reject,
    y = y
  )) +
  geom_bar(stat = "identity", color = "black") +
  scale_fill_manual(values = c("#E69F00", "white")) +
  scale_alpha_manual(values = c(0.1, 1))

right_plot <- cowplot::plot_grid(plot_1B, 
                   NULL,
                   cowplot::get_legend(
                   dummy_plot), NULL, nrow = 1, 
                   rel_widths = c(1, 0.1, 0.1, 0.1))


cowplot::plot_grid(plot_1A, 
                   NULL,
                   right_plot, 
                   nrow = 1, 
                   rel_widths = c(1, 0.15, 1.25))

```